---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.17.3
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

<!-- #region -->
# Data Types

```{note}
This page is partly adapted from by [Brett and co-authors (2023)](https://odsti.github.io/cfd-textbook/intro_to_functions.html). See the [license](https://github.com/pxr687/Intro_Comp_Programming/blob/main/license.md) page for more information.
```

So far we have used numbers and text in our Python code:
<!-- #endregion -->

```{python}
# A number.
42
```

```{python}
# Some text.
"Asok is a BTS Station."
```

We have also use *functions*, like `print()` with numbers *and* text:

```{python}
# The `print()` function.
print('This is the print function!')
```

```{python}
# The `print()` function with a number.
print(100)
```

We know that you can think of a function like a [*recipe*](https://www.inferentialthinking.com/chapters/08/Functions_and_Tables). We give it some ingredients, and it returns a "meal".

For the `print()` function, we give it some input and it displays the input.

```{python}
# The `print()` function (again).
print("This is a very long input, which as some text and the number", 100)
```

Text and numbers are different *Data Types* in Python.

It is very important to know what type of data you are using.

If you accidentally change a data type, it can lead to errors.

This is because operators (like `*`) do different things to different types of data.

For example, if we use `*` with numbers...

```{python}
# A number, multiplied by 10.
10 * 10
```

...then it multiplies them together. Just like in maths.

What about if we use it with text?

```{python}
# Text, multiplied by 10.
"This is text!" * 10
```

We can see that when we use `*` with text, it does something different. It *repeats* the text many times.

We need to know what type of data we are using, so that we know what our function will do. Using the function or operation with the wrong data type will break your code! 

A very common problem in data analysis is that data that should be *numbers* gets changed to *text* by accident.

Imagine we work for a company which pays a member of staff $1235 each month. We want to know how much our company pays them over 10 months. This is is easy to work out with numbers:

```{python}
# Cost of 10 months.
1235 * 10
```

But what if we put a `,` in the in data point for $1235? This can mean it gets changed to text. Then our calculation gives us a very strange result:

```{python tags=c("raises-exception")}
"1,235" * 10
```

We may not notice this error at first, if our code is very complex. But it will cause errors later...

For another example, let's look at the `round()` function, which will round a number with a decimal place.

If we give `4.2` as an argument to `round()`, it will return the value `4`. It removes the decimal place, and "rounds the number down" to `4`:

```{python}
# Use `round()` to remove a decimal place.
round(4.2)
```

If we give it a number where the decimal is above 0.5, it will "round up" to the nearest whole number:

```{python}
# `round()` again
round(10.9)
```

Lots of Python functions are made to work with one data type, and not others. You will get errors if you use the wrong data type.

For example, look what happens if we try to `round()` some text:

```{python tags=c("raises-exception")}
# Use `round()` with some text.
round("This is some text.")
```

You see that we get an error. Look at what the error says - it is a `TypeError`. This means we gave the `round()` function the wrong type of data.

## How to avoid errors: use `type()`

We can use the `type()` function with any literal, variable or expression, and it will tell us what type of data it evaluates to. This helps us know what data types we are using, to make sure they are what we want.

When we use the `type()` function, it is like asking Python "what type of data is this?":

```{python tags=c("raises-exception")}
# Use `type()` with some text.
type("This is some text.")
```

I have been using the word "text" for text data. The proper Python name for text is *string data*. This is what `str` means, in the output of the cell about. `type("This is some text")` returns `str` - this means that the literal `"This is some text"` is string data (text data).

What `type` is the number `1`?

```{python}
# Use `type()` with a number.
type(1)
```

This is telling us that `1` is an *integer*. This means it is a *whole number* - it does not have a decimal place.

What about a number like `4.2` with a decimal place, what `type()` is that?

```{python}
# `type()` with a different number.
type(4.2)
```

In Python, `float` just means something like "a number with a decimal place". `float` means the computer is representing the number as a [*floating point*](https://fabiensanglard.net/floating_point_visually_explained/) number. For now, you can just think of this as "a number with a decimal place".

We can use `type()` with all of the Python elements we have seen so far (literals, expressions, variables, functions). Here are something more examples:

```{python}
# Assign a numeric variable.
my_number = 10
```

```{python}
# Show the value of `my_number`.
my_number
```

```{python}
# Show the `type()` of the variable.
type(my_number)
```

```{python}
# Assign another numeric variable.
my_other_number = 10.0
```

```{python}
# Show the value of `my_other_number`.
my_other_number
```

```{python}
# Show the `type()` of `my_other_number`.
type(my_other_number)
```

Three of the basic data types in Python are:

- `str` : string/text data (e.g. `"BOY"`, `"GIRL"`)

- `int` : integer/whole number data, with *no* decimal places (e.g. `4`)

- `float` : floating point number data, *with* decimal places (e.g. `4.2`)


## Changing Data Types

[Can be done with built-in functions]

```{python}
my_int = 10

my_int
```

```{python}
my_float = float(my_int)

my_float
```

```{python}
type(my_int)
```

```{python}
type(my_float)
```

```{python}
my_string = str(my_float)

my_string
```

```{python}
type(my_string)
```

## Exercise 3 - Data Types

We will now do our third Python exercise!

*Remember*: your [assignments, tests and exams](https://pxr687.github.io/Intro_Comp_Programming/1_02_Class_Grades_Assignments_Exams.html) will also be a bit like this.

Click [here 🚀](https://mybinder.org/v2/gh/pxr687/Intro_Comp_Programming/main?urlpath=tree/exercise_3_datatypes_comparison_functions.ipynb) to launch the exercise on Binder.


----------------------------------------------------------

[🏡](intro.md).
