---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.17.3
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

<!-- #region -->
# Data Types, Comparison Operators and Functions

```{note}
This page is partly adapted from by [Brett and co-authors (2023)](https://odsti.github.io/cfd-textbook/intro_to_functions.html). See the [license](https://github.com/pxr687/Intro_Comp_Programming/blob/main/license.md) page for more information.
```

So far we have used numbers and text in our Python code:
<!-- #endregion -->

```{python}
# A number.
42
```

```{python}
# Some text.
"Asok is a BTS Station."
```

We have also use *functions*, like `print()` with numbers *and* text:

```{python}
# The `print()` function.
print('This is the print function!')
```

```{python}
# The `print()` function with a number.
print(100)
```

We know that you can think of a function like a [*recipe*](https://www.inferentialthinking.com/chapters/08/Functions_and_Tables). We give it some ingredients, and it returns a "meal".

For the `print()` function, we give it some input and it displays the input.

```{python}
# The `print()` function (again).
print("This is a very long input, which as some text and the number", 100)
```

Text and numbers are differ *Data Types* in Python.

It is very important to know what type of data you are using.

If you accidentally change a data type, it can lead to errors.

This is because operators (like `*`) do different things to different types of data.

For example, if we use `*` with numbers...

```{python}
# A number, multiplied by 10.
10 * 10
```

...then it multiplies them together.

What about if we use it with text?

```{python}
# Text, multiplied by 10.
"This is text!" * 10
```

The `round()` function will round a number with a decimal place.

So if we pass `4.2` as an argument to `round()`, it will return the value `4`. It removes the decimal place, and "rounds the number down" to `4`:

```{python}
# Use `round()` to remove a decimal place.
round(4.2)
```

If we give it a number where the decimal is above 0.5, it will "round up" to the nearest whole number:

```{python}
# `round()` again
round(10.9)
```

Remember I said that you should always know what *data type* you are using in Python? E.g. you should always know if you are using text or numbers?

This is because lots of Python functions are made to work with one data type, and not others. You will get errors if you use the wrong data type.

For example, look what happens if we try to `round()` some text:

```{python tags=c("raises-exception")}
# Use `round()` with some text.
round("This is some text.")
```

You see that we get an error. Look at what the error says - it is a `TypeError`. This means we gave the `round()` function the wrong type of data.

We can use the `type()` function with any literal, variable or expression, and it will tell us what type of data it evaluates to. When we use `type()` it is like asking Python "what type of data is this?":

```{python tags=c("raises-exception")}
# Use `type()` with some text.
type("This is some text.")
```

I have been using the word "text" for text data. The proper Python name for text is *string data*. This is what `str` means, in the output of the cell about.

What `type` is the number `1`?

```{python}
type(1)
```

```{python}
type("Hello world!")
```

```{python}
# 
help(type)
```

```{python tags=c("raises-exception")}
help(type())
```

```{python}
# Assign a numeric variable.
my_number = 10
```

```{python}
# Show the value of `my_number`.
my_number
```

```{python}
type(my_number)
```

```{python}
# Assign another numeric variable.
my_other_number = 10.0
```

```{python}
# Show the value of `my_other_number`.
my_other_number
```

```{python}
type(my_other_number)
```

[List of basic datatypes]


## Why is Data Type important?

...because the wrong data type will break your code!

```{python}
10 * 10
```

```{python tags=c("raises-exception")}
"10" * "10"
```

## Comparison operators and Booleans

- Explain link to literals, variables, expressions and datatypes.

- Explain importance with concrete example.

```{python}
10 == 10
```

```{python}
type(10 == 10)
```

```{python}
type(True)
```

```{python}
type("True")
```

```{python}
True * 10
```

```{python}
"True" * 10
```

```{python}
10 == 11
```

```{python}
10 < 10
```

```{python}
10 < 11
```

```{python}
10 > 10
```

```{python}
10 > 9
```

```{python}
10 != 11
```

```{python}
10 != 10
```

```{python}
# Equality comparison operator, with variables.
my_number == my_other_number
```

```{python}
my_extra_number = 200

# Show the value of `my_extra_number`
my_extra_number
```

```{python}
my_number == my_extra_number
```

```{python}
is_true = my_number == my_other_number

is_true
```

```{python}
type(is_true)
```

```{python}
is_false = my_number == my_extra_number

is_false
```

```{python}
type(is_false)
```

```{python}
"This string is the same" == "This string is the same"
```

```{python}
"This string is the same" == "This string is NOT the same"
```

```{python}
type("This string is the same" == "This string is NOT the same")
```

## Changing Data Types

[Can be done with built-in functions]

```{python}
my_int = 10

my_int
```

```{python}
my_float = float(my_int)

my_float
```

```{python}
type(my_int)
```

```{python}
type(my_float)
```

```{python}
my_string = str(my_float)

my_string
```

```{python}
type(my_string)
```

## The `dir()` function

```{python}
dir()
```

```{python}
LOOK_AT_ME_I_AM_A_NEW_VARIABLE = 99999
```

```{python}
dir()
```

## Exercise 3 - Data Types

We will now do our third Python exercise!

*Remember*: your [assignments, tests and exams](https://pxr687.github.io/Intro_Comp_Programming/1_02_Class_Grades_Assignments_Exams.html) will also be a bit like this.

Click [here 🚀](https://mybinder.org/v2/gh/pxr687/Intro_Comp_Programming/main?urlpath=tree/exercise_3_datatypes_comparison_functions.ipynb) to launch the exercise on Binder.


----------------------------------------------------------

[🏡](intro.md).
