---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.17.3
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Summary: Literals, Variables, Expressions and Functions

> Some advice before you read this page: 
> - Read *slowly* and make sure you fully understand each idea before you move on.
> - Launch the page on Live Code and Binder and play around with the code in each cell. Do this even if the idea seems easy.  You might think you understand, but you can still learn something by trying out something new with the idea.
> - Try to break the code, try to fix it.
> - Try something where you are not sure what will happen.
> - Then try to understand *why* something happens.
>
> *The best way to understand these ideas is to play with the code yourself*.
>
> The more you understand these ideas, the **easier** it will be for you to **fix errors** in your code.

Let's summarise what we have learned so far. We have learned about some of the basic *elements* (e.g. small pieces) of Python code. 

These elements can be put together to let us write complex Python programs. Python is a very powerful and useful language; so Python programs can be used for:

- data analysis + machine learning

- making apps

- talking to servers...

Almost anything you can think of that a computer can do can be done with Python, by putting together these elements...

...but before we do any of that fun stuff, let's make sure we understand the basic Python elements that we saw on earlier pages.

It is important for you to know these Python elemtns for two reasons:

1. For your [exams, tests and assignments](1_02_Class_Grades_Assignments_Exams).

2. It helps you understand, debug and fix *errors in your code*. Error messages often talk about literals, strings, expressions etc. You will often know *why* an error happened if you understand the ideas on this page.

## Literals

A raw number or piece of text typed in Python code is called a *literal*:

```{python}
100
```

```{python}
"text"
```

We type in the literal, and Python shows us the *value*. The value is the computer representation of the literal.

Literals are a type of *expression*, because Python shows us a value when we run a line of code which has only a literal.

Remember that an expression is *anything which returns a value*.

## Variables

We can store values as *variables*. This means we give the value a name. We can use that name to get the value out of our computer's memory:

```{python}
# This is a variable assignment statement. 
#`number_3` is the name of the variable, `3` is it's value.
number_3 = 3
```

The variable assignment statement in the cell above is *not* an expression. It does not show us a value when we run the line of code with the variable assignment statement.

The variable assignment statement *makes* a new variable (`number_3`).

After the variable is made, it is an expression, because it has a value:

```{python}
# The cell above this one created this variable `number_3`. This cell shows the value of the variable.
number_3
```

You can think of *literals* as values in Python code which are NOT stored as variables:

```{python}
# This is a literal.
1999
```

```{python}
# Store `1999` as a variable - this is a variable assignment statement.
new_variable = 1999
```

```{python}
# See what the value of `new_variable` is.
new_variable
```

Literals and variables are both types of *expression*. 

## Expressions

Expressions are any piece of Python code that returns a value.

So, in Jupyter, if you run a cell and you see an output, then the cell has an expression inside it.:

```{python}
# This is an expression (this expression is made from two literals)
2 + 2
```

```{python}
# This is NOT an expression, it is a *statement*. It is NOT an expression because it does not
# return a value.
four_as_variable = 2 + 2
```

The rule is: 

> If you run a line of code and Jupyter automatically shows you a value, the line is an *expression*.
> If you run a line of code and Jupyter does **NOT** automatically show a value, the line is a *statement*.

Let's look at this expression again:

```{python}
2 + 2
```

We say that an expression *evaluates* to a value. So in the cell above, the expression `2 + 2` *evaluates* to `4`. This is the same as saying the expression `2 + 2` returns the value `4`.

As said earlier, literals and variables are also expressions (the simplest kinds of expressions!), because they return a value:

```{python}
# This literal is also an expression, because it returns a value.
1990
```

```{python}
# This text literal is also an expression, because it returns a value.
"text"
```

```{python}
# This variable is also an expression, because it returns a value. (We made this variable earlier).
number_3
```

We can put literals and/or variables together to make expressions:

```{python}
# This is an expression (this expression is made from two variables we made earlier).
number_3 + new_variable
```

```{python}
# This is an expression made from a variable and a literal.
number_3 + 4000
```

We can store expressions as variables also (well, we store the *value* of the expression as a variable):

```{python}
# Store the expression `1000/3` as a variable named `one_thousand_divided_by_3`.
one_thousand_divided_by_3 = 1000/3
```

```{python}
# Show the value of the variable one_thousand_divided_by_3.
one_thousand_divided_by_3
```

We can also make expressions from text, e.g. by putting two text literals together with an operator like `+`:

```{python}
# An expression made from text.
"This is some text." + " And so is this!"
```

## Functions - the `print()` function

On earlier pages, we also used *functions*, like `print()`:

```{python}
# The `print()` function.
print('This is the print function!')
```

Functions are pieces of code that are written to do a specific thing. That code can then be used many many times without us needing to write it again.

You can think of a function like a [*recipe*](https://www.inferentialthinking.com/chapters/08/Functions_and_Tables). We give it some ingredients, and it returns a "meal".

**In Python, when you see a word like `print` next to *round brackets* `()` you are looking at a function e.g. `print()`**.

For the `print()` function, we give it some input and it displays the input. 

We can use the `print()` function to show us the value of any expression.

We have used `print()` with text, but we can also use it with numbers:

```{python}
# The `print()` function with a number.
print(10)
```

```{python}
# The `print()` function with text.
print("Hello class!")
```

### Other Python functions

There are many, many other functions we can use in Python.

Another example is the `abs()` function. This will remove a minus sign (`-`) from a negative number:

```{python}
# Make a negative number, store it in a variable called `my_negative_number`.
my_negative_number = -1

# Show the value of `my_negative_number`
my_negative_number
```

We can "give" `my_negative_number` to the `abs()` function. We do this by putting it inside the `()` brackets after the function name. For the `abs()` function, this will get rid of the minus sign (`-`) from `my_negative_number`:

```{python}
abs(my_negative_number)
```

We can also give `abs()` a literal (instead of a variable):

```{python}
abs(-9999)
```

We can also give it an expression made from literals:

```{python}
abs(-100 - 10)
```

And we can give it an expression made from variables:

```{python}
# An expression made from variables.
-number_3 - new_variable
```

```{python}
# Giving the same expression to the `abs()` function.
abs(-number_3 - new_variable)
```

We can also mix variables and literals together in an expression, and give that expression to `abs()`:

```{python}
# An expression made from a variable and a literal.
-number_3 - 1000
```

```{python}
# Giving `abs()` an expression made from a variable and a literal.
abs(-number_3 - 1000)
```

When we give literals, variables or expressions to a function we call them *arguments*.

We say that we "give an argument to a function" or we "pass an argument to a function".

So the cell below "passes the number literal `8888` to the `print()` function:

```{python}
print(8888)
```

The cell below passes the literal `"this is some text!"` to the `print()` function:

```{python}
print("this is some text!")
```

The cell below passes the expression `-10_000 - 800` to the `abs()` function:

```{python}
abs(-10_000 - 800)
```

The table below is a summary of this information:

| Python Element | What it is                                                       | Example 1 (Numbers) | Example 2 (Text) |
| -------------- | ---------------------------------------------------------------- | ------------------- | ---------------- |
| **Literal**    | A value written "raw" in Python code                             | `42`                | `"hello"`        |
| **Variable Assignment Statement**   | We use this to store a value in our computer's memory | `age = 42`| `name = "Sam"`   |
| **Variable**   | A name/value pair stored in our computer's memory                | `age`               | `name`           |
| **Expression** | Code that Python evaluates to produce a value                    | `1 + 1` ; `age + 1` | `name + "!"`     |
| **Function**   | Reusable code that does a task, usually using inputs/arguments   | `print(10)`         | `print("Hello")` |

Expressions can be made from literals and/or variables ... and other expressions!

**Note**: any definitions which are in the textbook may be asked about in your exams and assessments.

Functions can use literals, variables and expressions as inputs. This is shown in the cells below with the `print()` function:

```{python}
# Print a literal with the `print()` function. 
# The text "The capital of Thailand is Bangkok." is the *input* to the `print()` function.
print("The capital of Thailand is Bangkok.")
```

```{python}
# Print a variable with the `print()` function.
print(one_thousand_divided_by_3)
```

```{python}
# Print an expression with the `print()` function.
print(100**2 + 777)
```

```{python}
# Print a literal with the `print()` function. This is two text literals put together into an expression.
print("The capital of Thailand is Bangkok." + " London is the capital of England.")
```

## Python will only show you the value from the last line of code

When you run a code cell with an expression in it, Python will show you the value that the expression evaluates to:

```{python}
3 * 4
```

If the code cell has expressions on more than one line *Python will only show you the value of the last line*:

```{python}
3 * 4
10 + 10
```

You can use the `print()` function to make Python show you the value of all the expressions in the cell:

```{python}
print(3 * 4)
print(10 + 10)
```

This is the same way with numbers and with text data:

```{python}
"Hello!"
"Class!"
```

```{python}
print("Hello!")
print("Class!")
```

## Exercise - Literals, Expressions and Functions

We will now do our next Python exercise. This will check that you understand the concepts from this page.

*Remember*: your [assignments, tests and exams](https://pxr687.github.io/Intro_Comp_Programming/1_02_Class_Grades_Assignments_Exams.html) will also be a bit like this.

Click [here 🚀](https://mybinder.org/v2/gh/pxr687/Intro_Comp_Programming/main?urlpath=tree/exercise_2_literals_expressions_functions.ipynb) to launch the exercise on Binder.


----------------------------------------------------------

[🏡](intro.md).
