---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.17.3
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

<!-- #region -->
# String methods

```{note}
This page is adapted from [Brett, Rush, Adhikari, Denero and Wagner (2023)](https://odsti.github.io/cfd-textbook/String_Methods.html). See the [license](https://github.com/pxr687/Intro_Comp_Programming/blob/main/license.md) page for more information.
```

From a string, related strings can be made using string methods. String methods are functions that operate on strings. These methods are called by placing a dot after the string, then calling the function.

For example, the following method generates an uppercased (all capitals) version of a string.
<!-- #endregion -->

```{python}
"loud".upper()
```

Perhaps the most important method is `replace`, which replaces all instances of a substring within the string. The `replace` method takes two arguments, the text to be replaced and its replacement.

```{python}
'hitchhiker'.replace('hi', 'ma')
```

String methods can also be used with variable names, as long as the variable is a string. So, for instance, the following two-step process makes the word "degrade" starting from "train" by first creating "ingrain"
and then applying a second replacement.

```{python}
s = "train"
t = s.replace('t', 'ing')
u = t.replace('in', 'de')
u
```

Let's break that down to make it clearer what is happening:

```{python}
# The string we start with.
s
```

```{python}
# Replace "t" with "ing".
t = s.replace('t', 'ing')
t
```

```{python}
# Replace "in" with "de"
u = t.replace('in', 'de')
u
```

Note that the line `t = s.replace('t', 'ing')` doesn't change the string `s`,
which is still "train".  The method call `s.replace('t', 'ing')` just has
a value, which is the string "ingrain".

```{python}
s
```

This is the first time we've seen methods, but methods are not unique to strings.  As we will see shortly, other types of objects can have them.

## Exercise 4 - String Methods

We will now do another exercise!

*Remember*: your [assignments, tests and exams](https://pxr687.github.io/Intro_Comp_Programming/1_02_Class_Grades_Assignments_Exams.html) will also be a bit like this.

Click [here 🚀](https://mybinder.org/v2/gh/pxr687/Intro_Comp_Programming/main?urlpath=tree/exercise_4_string_methods.ipynb) to launch the exercise on Binder.

----------------------------------------------------------

[🏡](intro.md).
