---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.19.5
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Data Types and the `type()` function

```{note}
This page is partly adapted from [Brett, Rush, Adhikari, Denero and Wagner (2023)](https://odsti.github.io/cfd-textbook/data_types.html). See the [license](https://github.com/pxr687/Intro_Comp_Programming/blob/main/license.md) page for more information.
```

> Some advice before you read the pages in this section: 
> - Read *slowly* and make sure you fully understand each idea before you move on.
> - Launch the page on Live Code and Binder and play around with the code in each cell. Do this even if the idea seems easy.  You might think you understand, but you can still learn something by trying out something new with the idea.
> - Try to break the code, try to fix it.
> - Try something where you are not sure what will happen.
> - Then try to understand *why* something happens.
>
> *The best way to understand these ideas is to play with the code yourself*.
>
> The more you understand these ideas, the **easier** it will be for you to **fix errors** in your code.  

So far we have used numbers and text in our Python code:

```{python}
# A number.
42
```

```{python}
# Some text.
# Note: we need quotation marks (" or ') at the start and end of text data.
"Bang Wa has a BTS and MRT station."
```

In each cell above, look at the *colour* of the number and the text. You can see that Jupyter shows you them in different colours. This is called [syntax highlighting](https://en.wikipedia.org/wiki/Syntax_highlighting) - this just means that Jupyter (or other software which uses Python) shows different types of thing in different colours. 

You can think of "syntax" as another word for "grammar" - different elements in Python grammar are shown as different colours, to make it easy for us to see that they are different.

We have also use *functions*, like `print()` with numbers *and* text:

```{python}
# The `print()` function.
print('This is the print function, it is printing some text!')
```

```{python}
# The `print()` function with a number.
print(100)
```

We know that you can think of a function like a [*recipe*](https://www.inferentialthinking.com/chapters/08/Functions_and_Tables). We give it some ingredients, and it returns a "meal".

For the `print()` function, we give it some input and it displays the input. Here we use `print()` with some text AND and number. We do this by putting a `,` in between the text and the number. Again, look at the colour of the text and the colour of the number:

```{python}
# The `print()` function (again, with text and a number).
print("This is a very long input, which as some text and the number", 100)
```

We can also use variables, within `print()`, also by using a `,`:

```{python}
# The `print()` function (again, this time with a variable).
number_variable = 3765
print("This is a very long input, which as some text and another number, which is", number_variable)
```

Text and numbers are different *Data Types* in Python. Different data types have different rules for how we use them.

**It is very important to know what type of data you are using.**

If you accidentally change a data type, it can lead to errors. Something that is OK for one type of data can break a Python rule for another type of data.

This is because operators (like `*`) do different things to different types of data.

For example, if we use `*` with numbers...

```{python}
# A number, multiplied by 10.
10 * 10
```

...then it multiplies them together. Just like in maths.

What about if we use it with text?

```{python}
# Text, multiplied by 10.
"This is text!" * 10
```

We can see that when we use `*` with text, it does something different. It *repeats* the text many times.

We need to know what type of data we are using, so that we know what our function will do. 

**Using the function or operation with the wrong data type will break your code!**

## Data type errors

A very common problem in data analysis is that data that should be *numbers* gets changed to *text* by accident.

Imagine we work for a company which pays a member of staff $1235 each month. We want to know how much our company pays them over 10 months. This is is easy to work out with numbers:

```{python}
# Cost of 10 months.
1235 * 10
```

But what if we put a `,` in the in data point for $1235? This can mean it gets changed to text. Then our calculation gives us a very strange result:

```{python tags=c("raises-exception")}
"1,235" * 10
```

We may not notice this error at first, if our code is very complex. But it will cause errors later...

**In the code cell above `"1,235"` *looks* like a number but actually it is text.** We know that it is text because of the quotation marks (`"`). But it can trick us into thinking it is a number, which can cause errors.

```{python}
# This IS a number.
1235
```

```{python}
# This *looks* like a number, but it is text. (Look at the quotation marks "")...
"1,235"
```

For another example, let's look at the `round()` function, which will round a number with a decimal place.

If we give `4.2` as an argument to `round()`, it will return the value `4`. It removes the decimal place, and "rounds the number down" to `4`:

```{python}
# Use `round()` to remove a decimal place.
round(4.2)
```

If we give it a number where the decimal is above 0.5, it will "round up" to the nearest whole number:

```{python}
# `round()` again
round(10.9)
```

Lots of Python functions are made to work with one data type, and not others. You will get errors if you use the wrong data type.

For example, look what happens if we try to `round()` some text:

```{python tags=c("raises-exception")}
# Use `round()` with some text.
round("This is some text.")
```

You see that we get an error. Look at what the error says - it is a `TypeError`. This means we gave the `round()` function the wrong type of data.

Text which *looks* like a number can be a problem here:

```{python tags=c("raises-exception")}
# "4.2" *looks* like a number, but actually it is text, so we get an error...
round("4.2")
```

## How to avoid errors: use `type()`

We can use the `type()` function with any literal, variable or expression, and it will tell us what type of data it evaluates to. This helps us know what data types we are using, to make sure they are what we want, so that we can avoid errors.

When we use the `type()` function, it is like asking Python "what type of data is this?". So, the code below asks:

>  "What type of thing is `"This is some text."`?":

```{python tags=c("raises-exception")}
# Using `type()` with some text.
type("This is some text.")
```

I have been using the word "text" for text data. The proper Python name for text is *string data*. This is what `str` means, in the output of the cell about. `type("This is some text")` returns `str` - this means that the literal `"This is some text"` is string data (text data).

What `type` is the number `1`?

```{python}
# Use `type()` with a number.
type(1)
```

This is telling us that `1` is an *integer*. This means it is a *whole number* - it does not have a decimal place.

What about a number like `4.2` with a decimal place, what `type()` is that?

```{python}
# `type()` with a different number.
type(4.2)
```

In Python, `float` just means something like "a number with a decimal place". `float` means the computer is representing the number as a [*floating point*](https://fabiensanglard.net/floating_point_visually_explained/) number. For now, you can just think of this as "a number with a decimal place".

We can use `type()` with all of the Python elements we have seen so far (literals, expressions, variables, functions). Here are something more examples:

```{python}
# Assign a numeric variable.
my_number = 10
```

```{python}
# Show the value of `my_number`.
my_number
```

```{python}
# Show the `type()` of the variable.
type(my_number)
```

```{python}
# Assign another numeric variable.
my_other_number = 10.0
```

```{python}
# Show the value of `my_other_number`.
my_other_number
```

```{python}
# Show the `type()` of `my_other_number`.
type(my_other_number)
```

Three of the basic data types in Python are:

- `str` : string/text data (e.g. `"BOY"`, `"GIRL"`)

- `int` : integer/whole number data, with *no* decimal places (e.g. `4`)

- `float` : floating point number data, *with* decimal places (e.g. `4.2`)

We will talk more about numbers of the next page.


----------------------------------------------------------

[🏡](intro.md).
