---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.19.5
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

<!-- #region -->
# Lists

```{note}
This page is adapted from [Brett, Rush, Adhikari, Denero and Wagner (2023)](https://odsti.github.io/cfd-textbook/lists.html). See the [license](https://github.com/pxr687/Intro_Comp_Programming/blob/main/license.md) page for more information.
```


Thus far we have seen the following data types:

* integer (counting number) - `int`.
* floating point number (number with decimal point) - `float`.
* string (text) - `str`.
* boolean (True or False value) - `bool`.

For computing and data analysis, we often want to put together several numbers, or
strings, into a *group* or *collection*.  This allows us to collect values together into one
place, and refer to all the values with a single name.  Now that we can refer
to all the values with a single name, we can write code that works on the whole
group at once.

For example, remember our [problem of the three girls in a family of four](1_04_A_Simple_Problem.)?

You have seen that we can make four random values, that can be `"BOY"` or `"GIRL"`, like this:
<!-- #endregion -->

```{python}
# Load the Numpy package, and rename to "np"
import numpy as np

# Get four simulated children (50% chance of "BOY", 50% chance of "GIRL")
a = np.random.choice(['GIRL', 'BOY'])
b = np.random.choice(['GIRL', 'BOY'])
c = np.random.choice(['GIRL', 'BOY'])
d = np.random.choice(['GIRL', 'BOY'])
```

Here, each child number gets their own variable.

```{python}
a
```

```{python}
b
```

```{python}
c
```

```{python}
d
```

This gave us one simulated family.

Now imagine that we were trying to simulate a family of 12 children.  We would
have to give each child their own variable `a` through `l` (small L), and then
type 12 lines of code to see the value of the variables.

That would be annoying, and impractical when we have to simulate
larger numbers, such as the 100 families.

Groups are part of the solution to this problem. Groups (also called
*sequences* or *collections* can store lots of other values/variables. 
There are two main types of collection, in Python:

* Lists - `list`
* Arrays - `np.array`

We will see arrays soon. This page is about *lists*.


## Making a list

You make a list using *square brackets* - `[` and `]`.

Here we make a list that contains three integers:

```{python}
my_numbers = [1, 2, 3]
my_numbers
```

As always, we can check the data type of `my_numbers` using the `type()` function:

```{python}
type(my_numbers)
```

More formally, you define a list like this:

1. the open square bracket character `[`, followed by
1. a sequence of zero of more values, separated by commas, followed by
1. the close square bracket character `]`.

`[1, 2, 3]` is a *list expression* because it is a recipe that results in
a value that is a list).  We confirm it is an expression by showing that the notebook displays a value:

```{python}
[1, 2, 3]
```

What `type` of value is it?

```{python}
type(my_numbers)
```

Here is a list with one value:

```{python}
another_list = [99]
another_list
```

Lists can be empty.  To make an empty list, put nothing inside the square brackets, like this:

```{python}
my_empty_list = []
my_empty_list
```

A list can have any kind of value as its elements.  For example, here is a list of strings:

```{python}
some_strings = ["Chris", "Andre", "Jessica", "Luke"]
some_strings
```

## Getting things out of a list

Each thing in a Python list is called a *list element*.

We can get a list element out of a list by using *list indexing*.

"Indexing" just means using Python commands to get data out of a *collection*. A *collection* is a Python object that can hold more than one thing (e.g. more than one text literal, more than one variable etc).

**This is important:** in Python when we count the elements in a collection, **we start counting from 0, not from 1**. 

So, to get the *first* element from the `some_strings` list we use this command:

```{python}
# Get the first element of `some_strings`.
some_strings[0]
```

Here we have the name of the list (`some_strings`) then we use square brackets (`[]`) with a number inside them. The number is the *list index*. The list index `[0]` gets the first piece of data from the list.

To get the *second* list element, we use:

```{python}
# Get the second element of `some_strings`.
some_strings[1]
```

To get the *third* list element we use:

```{python}
# Get the third element of `some_strings`.
some_strings[2]
```

To get the *fourth* list element we use:

```{python}
# Get the fourth element of `some_strings`.
some_strings[3]
```

Look again at the whole list to see that this is correct:

```{python}
some_strings
```

The rule to remember this is:

> Take the number of the data you want (e.g. the third element of the list), then subtract 1 to get the correct list index.

So if you want the *fourth* element, this is at list index 3:

```{python}
# Get the fourth element of `some_strings`.
print(f'Here is the whole `some_strings` list {some_strings}')
print('The line of code below gets the *fourth* element of the list:')
some_strings[3]
```

## Functions and lists

Python has some built-in functions that operate on sequences, like lists.

A built-in function is a function that we can use in any Python session,
without `import`ing it from a library.

One of these built-in functions is `len`.  Here is a *call expression*, using
the function `len` on our list:

```{python}
len(my_numbers)
```

As you might predict, calling `len` with the list as an argument, returns the number of elements in the list.

Another function that operates on lists is `sum`.  This adds all the elements in the list together, and returns the result:

```{python}
sum(my_numbers)
```

## A half-solution for three girls

Now we have another way of solving the problem of making the family of four
children above.  Use Control-Enter a few times on the cell below to see a new
family simulated every time:

```{python}
# Get four simulated children and put them in a list.
# The opening square brackets tell Python the statement is not finished
# when it reaches the end of the first line.
family =  [np.random.choice(['GIRL', 'BOY']),
           np.random.choice(['GIRL', 'BOY']),
           np.random.choice(['GIRL', 'BOY']),
           np.random.choice(['GIRL', 'BOY'])]
# Show the family.
family
```

*Note:* `np.str_` just tells us these are Numpy's version of `str` data...

We can use the *list method* `.count()` to count the number of girls in this family. Remember a method is a function attached to an object, like a list:

```{python}
# Count the number of girls.
family.count("GIRL")
```

The cell below simulates a new family, and the last line counts the number of girls in this family:

```{python}
# Get four simulated children and put them in a list.
# The opening square brackets tell Python the statement is not finished
# when it reaches the end of the first line.
family =  [np.random.choice(['GIRL', 'BOY']),
           np.random.choice(['GIRL', 'BOY']),
           np.random.choice(['GIRL', 'BOY']),
           np.random.choice(['GIRL', 'BOY'])]
# Show the family.
print(family)
family.count('GIRL')
```

We *could* run this code lots of times and write down the number of girls in each family. That would answer our question "what is the probability of a family of 4 having 3 girls?".

That would take a long time. On the next textbook pages, we will learn some more Python tools to make this process faster and more efficient...


## Exercise - Lists

We will now do another exercise!

*Remember*: your [assignments, tests and exams](https://pxr687.github.io/Intro_Comp_Programming/1_02_Class_Grades_Assignments_Exams.html) will also be a bit like this.

Click [here 🚀](https://mybinder.org/v2/gh/pxr687/Intro_Comp_Programming/main?urlpath=tree/exercise_4c_lists.ipynb) to launch the exercise on Binder.


----------------------------------------------------------

[🏡](intro.md).
