---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.17.3
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

<!-- #region -->
# String methods

```{note}
This page is adapted from [Brett, Rush, Adhikari, Denero and Wagner (2023)](https://odsti.github.io/cfd-textbook/String_Methods.html). See the [license](https://github.com/pxr687/Intro_Comp_Programming/blob/main/license.md) page for more information.
```

When you have a string, you can make new strings from it using string methods. String methods are *functions* that *work on strings*. These methods are used by putting a dot after the string, then calling the function.

For example, the following method generates an uppercase (all capitals) version of a string.
<!-- #endregion -->

```{python}
# Use the `.upper()` string method with the string `loud`.
"loud".upper()
```

```{python}
# Use the `.upper()` string method with the string `shouting`.
"shouting".upper()
```

We already saw the next string method on an earlier page. It is probably the most important string method - it is called `.replace()`. What it does is *replace* a substring within the string. The `.replace()` method takes two arguments, the text to replace and the text to replace it with.

```{python}
# Use the `.replace()` string method with the string `"sunny"`.
'sunny'.replace('s', 'f')
```

```{python}
# Use the `.replace()` string method with the string `"drink"`.
'drink'.replace('dr', 'th')
```

String methods can also be used with variables, if the variable is a string. 

So, for instance, the following code cell makes the word "money" starting from "many" by first making "my", and then doing another replacement after that.

```{python}
# Our first word, "many".
first_word = "many"

# Use `.replace()` to make our second word ("my").
second_word = first_word.replace('an', '')

# Use `.replace()` to make our third word ("money")
third_word  = second_word.replace('y', 'oney')
third_word
```

Let's break that down to make it clearer what is happening:

```{python}
# The string we start with.
first_word
```

```{python}
# Use `.replace()` to make our second word ("my").
second_word = first_word.replace('an', '')
second_word
```

```{python}
# Replace "in" with "de"
third_word  = second_word.replace('y', 'oney')
third_word
```

Notice that the line `second_word = first_word.replace('an', '')` does **NOT** change the string `first_word`,
which is still "many". 

```{python}
first_word
```

Methods are not only used with strings.  As we will see on other pages, other types of objects can have them.

## Exercise 4 - String Methods

We will now do another exercise!

*Remember*: your [assignments, tests and exams](https://pxr687.github.io/Intro_Comp_Programming/1_02_Class_Grades_Assignments_Exams.html) will also be a bit like this.

Click [here 🚀](https://mybinder.org/v2/gh/pxr687/Intro_Comp_Programming/main?urlpath=tree/exercise_4_string_methods.ipynb) to launch the exercise on Binder.

----------------------------------------------------------

[🏡](intro.md).
