# Book settings
title : "Introduction to Computer Programming"
author: Peter Rush
copyright: "2026"
logo: images/logo.jpg
email: pxr_687@outlook.com
# >- starts a multiline string, where newlines replaced by spaces, and final
# newlines are stripped.
description: >-
  Course textbook for September 2026 Introduction to Computer Programming

execute:
  # 'cache' attempts to cache the results.
  # 'auto' appears to be safer.
  execute_notebooks: cache
  timeout: 180

exclude_patterns:
  - README.md
  - todo.md
  - _notes/*
  - _to_ignore.md
  - images/LICENSE.md
  - data/README.md
  - .pytest_cache/*
  - .ipynb_checkpoints/*

html:
  favicon: images/logo.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://github.com/pxr687/Intro_Comp_Programming

repository:
  url: https://github.com/pxr687/Intro_Comp_Programming
  branch: main

launch_buttons:
  # The interface interactive links will activate ["classic", "jupyterlab"]
  notebook_interface: "classic"
  binderhub_url: "https:///mybinder.org"  # The URL for your BinderHub (e.g., https:///mybinder.org)

sphinx:
  recursive_update: true
  config:
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd

  extra_extensions:
    # For documenting 'click' Python CLIs
    # - sphinx_click.ext
    # Directive for creating tab panels in pages.
    # https:///github.com/djungelorm/sphinx-tabs
    # - sphinx_tabs.tabs
    # A sphinx extension for creating panels in a grid layout or as
    # drop-downs.
    # - sphinx_panels
    # Needed as of 5 Dec 2022 - release of IPython 8.7.0
    # https:///github.com/ipython/ipython/issues/13845
    # Fix from:
    # https:///github.com/spatialaudio/nbsphinx/issues/24#issuecomment-267687633
    # Alternative is to pin install to !=8.7.0
    - IPython.sphinxext.ipython_console_highlighting
    - sphinx_exercise

latex:
  latex_documents:
    targetname: odsti_textbook.tex

bibtex_bibfiles:
  - pandas_pages.bib

# HTML redirection
# Pages linked, but then renamed.
redirection:
  builddir: _build/html
  redirects:
    # data-types/Ranges: ../arrays/Ranges
