# Changing Data Types, using the `int()`, `float()` and `str()` functions

We know that three of the basic data types in Python are:

- `int` : integer/whole number data, with *no* decimal places (e.g. `4`)

- `float` : floating point number data, *with* decimal places (e.g. `4.2`)

- `str` : string/text data (e.g. `"BOY"`, `"GIRL"`)

If you see that your data is the wrong type - and you want to change it to the right type - there a many Python functions to do this. For example, we can use `float()` to change an `int` to a `float`:

In [1]:
# Create a variable containing an `int`.
my_int = 10

# Show the value of `my_int`
my_int

10

In [2]:
# Show the `type()` of `my_int`.
type(my_int)

int

To change `my_int` to the `float` data type, we just give it as an argument to the `float()` function:

In [3]:
# Change `my_int` to a `float`.
float(my_int)

10.0

You can see in the output of the cell above that the number now has a decimal place. 

Note: the proper name for changing the type of a variable in Python is [*casting*](https://www.w3schools.com/python/python_casting.asp). You will see this name in error message, so it is important to know. So, these two sentences have exactly the same meaning:

> 1. The cell above changes the variable `my_int` to the `float` data type, by using the `float()` function.

> 2. The cell above *casts* the variable `my_int` to the `float` data type, by using the `float()` function.

As always, we can store our new `float` in a variable:

In [4]:
# Store our `float` in a variable.
my_float = float(my_int)

# Show the value of `my_float`.
my_float

10.0

In [5]:
# Show the `type()` of `my_float`.
type(my_float)

float

We can change our data back to the `int` type using the `int()` function:

In [6]:
int(my_float)

10

Notice that the decimal place has disappeared...

If we want to change a number (`float` or `int`) to text (`str`), we can do this with the `str()` function:

In [7]:
# Change `my_float` to `str`.
my_string = str(my_float)

# Show the value of `my_string`.
my_string

'10.0'

Look closely at the output of the cell above. Notice the quotation marks (`''`) around `'10.0'`. These tell us it is a string, not a number. We can check this with the `type()` function:

In [8]:
# Show the `type()` of `my_string`.
type(my_string)

str

Importantly, `str()` (with brackets at the end) is a function to change something into a string. However, `str` (with no brackets at the end) is a Python data type (string/text data). 

Remember earlier I said that a common error is that a number gets changed *by accident* to text?:

In [9]:
# Should be a number, but it is text.
salary = "1,235"

This causes strange results when we try to do maths with the variable:

In [10]:
# Ouch!
salary * 10

'1,2351,2351,2351,2351,2351,2351,2351,2351,2351,235'

It will also cause errors when we use the variable with functions that want numbers as their arguments:

In [11]:
# Ouch! (again).
int(salary)

ValueError: invalid literal for int() with base 10: '1,235'

We will talk more about string data on another page. But we can fix this error by doing using *string methods* by removing the `,` from the `salary` variable:

In [12]:
# Re-assign the variable, with no ",".
salary = "1235"

# Show the value of `salary`.
salary

'1235'

`1235` is a string that the `int` function can work with!. Strings like `"1235"` are called *numeric strings* because they are in the right format for Python to change them into the `int` or `float` data types:

In [13]:
int(salary)

1235

Phew! Now it is a number again:

In [14]:
salary_as_int = int(salary)
type(salary_as_int)

int

... and we can do maths with it, without errors!:

In [15]:
# Calculate the salary over 10 months.
salary_as_int * 10

12350

By contrast, the string `"1,235"` is a *non-numeric string* because Python cannot easily change it into a number using the `int()` or `float()` functions - it is not written in the right way for this to work...

The table below shows a summary of the information on this page.

| Function | What it does | Works on | Examples | Result |
|---|---|---|---|---|
| `str()` | Changes a value to a **string** | Almost any Python value | `str(123)` | `"123"` |
| `int()` | Changes a value to an **integer** | Integers, whole-number floats, numeric strings | `int("123")` | `123` |
| `float()` | Changes a value to a **floating-point (e.g. decimal) number** | Integers, floats, numeric strings | `float("3.14")` | `3.14` |

## Printing different data types together

Like the `int()` and `float()` function will change data to `int` or `float`, we know that the `str()` function will change data into the `str` data type. Using this function, strings can be put together from more than one value.
One good thing about this is that it lets you `print()` different data types together:

In [16]:
# Combining different data types into a string.
"That's " + str(1 + 1) + ' ' + str(True) + " pal!"

"That's 2 True pal!"

In [17]:
# Using the `str()` function again to turn numbers into strings.
"There are " + str(50) + " districts in Bangkok."

'There are 50 districts in Bangkok.'

This can be very useful when you are debugging/fixing code, because you can `print()` out that value of a variables from different parts of the code, which can let you find where errors are happening.

We can also put number variables into the string, using the `str()` function:

In [18]:
number_of_students = 22

In [19]:
"There are " + str(number_of_students) + " students in the class."

'There are 22 students in the class.'

## Exercise: Data Types

*Remember*: your [assignments, tests and exams](https://pxr687.github.io/Intro_Comp_Programming/1_02_Class_Grades_Assignments_Exams.html) will also be a bit like this.

Click [here 🚀](https://mybinder.org/v2/gh/pxr687/Intro_Comp_Programming/main?urlpath=tree/exercise_2b_data_types.ipynb) to launch the exercise on Binder..

----------------------------------------------------------

[🏡](intro.md).